// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package icalendarmodule.proxies;

/**
 * 
 */
public class AppointmentSelectionHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject appointmentSelectionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "iCalendarModule.AppointmentSelectionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AppointmentSelectionHelper_Appointment("iCalendarModule.AppointmentSelectionHelper_Appointment");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AppointmentSelectionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "iCalendarModule.AppointmentSelectionHelper"));
	}

	protected AppointmentSelectionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject appointmentSelectionHelperMendixObject)
	{
		if (appointmentSelectionHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("iCalendarModule.AppointmentSelectionHelper", appointmentSelectionHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a iCalendarModule.AppointmentSelectionHelper");

		this.appointmentSelectionHelperMendixObject = appointmentSelectionHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AppointmentSelectionHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static icalendarmodule.proxies.AppointmentSelectionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return icalendarmodule.proxies.AppointmentSelectionHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static icalendarmodule.proxies.AppointmentSelectionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new icalendarmodule.proxies.AppointmentSelectionHelper(context, mendixObject);
	}

	public static icalendarmodule.proxies.AppointmentSelectionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return icalendarmodule.proxies.AppointmentSelectionHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AppointmentSelectionHelper_Appointment
	 */
	public final icalendarmodule.proxies.Appointment getAppointmentSelectionHelper_Appointment() throws com.mendix.core.CoreException
	{
		return getAppointmentSelectionHelper_Appointment(getContext());
	}

	/**
	 * @param context
	 * @return value of AppointmentSelectionHelper_Appointment
	 */
	public final icalendarmodule.proxies.Appointment getAppointmentSelectionHelper_Appointment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		icalendarmodule.proxies.Appointment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AppointmentSelectionHelper_Appointment.toString());
		if (identifier != null)
			result = icalendarmodule.proxies.Appointment.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AppointmentSelectionHelper_Appointment
	 * @param appointmentselectionhelper_appointment
	 */
	public final void setAppointmentSelectionHelper_Appointment(icalendarmodule.proxies.Appointment appointmentselectionhelper_appointment)
	{
		setAppointmentSelectionHelper_Appointment(getContext(), appointmentselectionhelper_appointment);
	}

	/**
	 * Set value of AppointmentSelectionHelper_Appointment
	 * @param context
	 * @param appointmentselectionhelper_appointment
	 */
	public final void setAppointmentSelectionHelper_Appointment(com.mendix.systemwideinterfaces.core.IContext context, icalendarmodule.proxies.Appointment appointmentselectionhelper_appointment)
	{
		if (appointmentselectionhelper_appointment == null)
			getMendixObject().setValue(context, MemberNames.AppointmentSelectionHelper_Appointment.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AppointmentSelectionHelper_Appointment.toString(), appointmentselectionhelper_appointment.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return appointmentSelectionHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final icalendarmodule.proxies.AppointmentSelectionHelper that = (icalendarmodule.proxies.AppointmentSelectionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "iCalendarModule.AppointmentSelectionHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
