// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package icalendarmodule.proxies;

/**
 * 
 */
public class Appointment extends icalendarmodule.proxies.AppointmentTemplate
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "iCalendarModule.Appointment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UID("UID"),
		UpdateSequence("UpdateSequence"),
		StartDateTime("StartDateTime"),
		EndDateTime("EndDateTime"),
		Subject("Subject"),
		BodyText("BodyText"),
		RecipientEmailAddress("RecipientEmailAddress"),
		SenderEmailAddress("SenderEmailAddress"),
		Location("Location");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Appointment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "iCalendarModule.Appointment"));
	}

	protected Appointment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject appointmentMendixObject)
	{
		super(context, appointmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("iCalendarModule.Appointment", appointmentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a iCalendarModule.Appointment");
	}

	/**
	 * @deprecated Use 'Appointment.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static icalendarmodule.proxies.Appointment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return icalendarmodule.proxies.Appointment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static icalendarmodule.proxies.Appointment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new icalendarmodule.proxies.Appointment(context, mendixObject);
	}

	public static icalendarmodule.proxies.Appointment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return icalendarmodule.proxies.Appointment.initialize(context, mendixObject);
	}

	public static java.util.List<icalendarmodule.proxies.Appointment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<icalendarmodule.proxies.Appointment> result = new java.util.ArrayList<icalendarmodule.proxies.Appointment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//iCalendarModule.Appointment" + xpathConstraint))
			result.add(icalendarmodule.proxies.Appointment.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final icalendarmodule.proxies.Appointment that = (icalendarmodule.proxies.Appointment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "iCalendarModule.Appointment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
